# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-16 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='item_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
