# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-16 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_menu_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='item_name',
            field=models.CharField(max_length=255),
        ),
    ]
