# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-29 02:54
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20190115_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(null=True, upload_to='menu_item_image'),
        ),
    ]
